#! /bin/bash
#PBS -l nodes=compute-0-0:ppn=16
#PBS -N SP_C6H5_R2_Anion
#PBS -j oe
cd $PBS_O_WORKDIR

job=C6H5_R2_Anion

cat $PBS_NODEFILE > pbsnodes
mkdir /tmp/$job
cp $job.*  /tmp/$job/
cd /tmp/$job
g09 $job.com
cp -r * $PBS_O_WORKDIR
cd ..
rm -rf /tmp/$job/
