#! /bin/bash
#PBS -l nodes=compute-0-0:ppn=16
#PBS -N opt_PHENAZINE_neutral
#PBS -j oe
cd $PBS_O_WORKDIR

job=PHENAZINE_neutral

cat $PBS_NODEFILE > pbsnodes
mkdir /tmp/$job
cp $job.*  /tmp/$job/
cd /tmp/$job
g09 $job.com
cp -r * $PBS_O_WORKDIR
cd ..
rm -rf /tmp/$job/
